import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const budgetPlans = [
  {
    name: "Gideon Petra",
    slug: "gideon-petra",
    priceMonthly: "6.00",
    ramMb: 4096,
    ramLabel: "4 GB RAM DDR5",
    cpu: "Ryzen 9 7950X",
    storageGb: 50,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 3,
    databases: 5,
    dedicatedIpPrice: "3.00",
    locations: ["Kansas City", "Miami, Florida"],
    isPopular: false,
    sortOrder: 1,
  },
  {
    name: "Gideon Carbizo",
    slug: "gideon-carbizo",
    priceMonthly: "9.00",
    ramMb: 6144,
    ramLabel: "6 GB RAM DDR5",
    cpu: "Ryzen 9 7950X",
    storageGb: 50,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 3,
    databases: 5,
    dedicatedIpPrice: "3.00",
    locations: ["Kansas City", "Miami, Florida"],
    isPopular: true,
    sortOrder: 2,
  },
  {
    name: "Gideon Aluminis",
    slug: "gideon-aluminis",
    priceMonthly: "12.00",
    ramMb: 8192,
    ramLabel: "8 GB RAM DDR5",
    cpu: "Ryzen 9 7950X",
    storageGb: 50,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 3,
    databases: 5,
    dedicatedIpPrice: "3.00",
    locations: ["Kansas City", "Miami, Florida"],
    isPopular: false,
    sortOrder: 3,
  },
  {
    name: "Gideon Cuprum",
    slug: "gideon-cuprum",
    priceMonthly: "18.00",
    ramMb: 12288,
    ramLabel: "12 GB RAM DDR5",
    cpu: "Ryzen 9 7950X",
    storageGb: 50,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 3,
    databases: 7,
    dedicatedIpPrice: "3.00",
    locations: ["Kansas City", "Miami, Florida"],
    isPopular: false,
    sortOrder: 4,
  },
  {
    name: "Gideon Ferrum",
    slug: "gideon-ferrum",
    priceMonthly: "24.00",
    ramMb: 16384,
    ramLabel: "16 GB RAM DDR5",
    cpu: "Ryzen 9 7950X",
    storageGb: 50,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 3,
    databases: 7,
    dedicatedIpPrice: "3.00",
    locations: ["Kansas City", "Miami, Florida"],
    isPopular: false,
    sortOrder: 5,
  },
];

const performancePlans = [
  {
    name: "Gideon Acerus",
    slug: "gideon-acerus",
    priceMonthly: "16.00",
    ramMb: 8192,
    ramLabel: "8 GB RAM DDR5",
    cpu: "Ryzen 9 9950X",
    storageGb: 75,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 5,
    databases: 10,
    dedicatedIpPrice: "3.00",
    locations: ["Miami, Florida"],
    isPopular: false,
    sortOrder: 6,
  },
  {
    name: "Gideon Argenix",
    slug: "gideon-argenix",
    priceMonthly: "24.00",
    ramMb: 12288,
    ramLabel: "12 GB RAM DDR5",
    cpu: "Ryzen 9 9950X",
    storageGb: 75,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 5,
    databases: 10,
    dedicatedIpPrice: "3.00",
    locations: ["Miami, Florida"],
    isPopular: false,
    sortOrder: 7,
  },
  {
    name: "Gideon Aurum",
    slug: "gideon-aurum",
    priceMonthly: "32.00",
    ramMb: 16384,
    ramLabel: "16 GB RAM DDR5",
    cpu: "Ryzen 9 9950X",
    storageGb: 75,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 5,
    databases: 10,
    dedicatedIpPrice: "3.00",
    locations: ["Miami, Florida"],
    isPopular: false,
    sortOrder: 8,
  },
  {
    name: "Gideon Rhodium",
    slug: "gideon-rhodium",
    priceMonthly: "48.00",
    ramMb: 24576,
    ramLabel: "24 GB RAM DDR5",
    cpu: "Ryzen 9 9950X",
    storageGb: 100,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 7,
    databases: 12,
    dedicatedIpPrice: "3.00",
    locations: ["Miami, Florida"],
    isPopular: false,
    sortOrder: 9,
  },
  {
    name: "Gideon Adamas",
    slug: "gideon-adamas",
    priceMonthly: "64.00",
    ramMb: 32768,
    ramLabel: "32 GB RAM DDR5",
    cpu: "Ryzen 9 9950X",
    storageGb: 100,
    backups: 3,
    extraBackupSlots: 3,
    extraBackupPrice: "1.50",
    ports: 7,
    databases: 12,
    dedicatedIpPrice: "3.00",
    locations: ["Miami, Florida"],
    isPopular: false,
    sortOrder: 10,
  },
  {
    name: "Gideon Adamas+",
    slug: "gideon-adamas-plus",
    priceMonthly: "96.00",
    ramMb: 49152,
    ramLabel: "48 GB RAM DDR5",
    cpu: "Ryzen 9 9950X",
    storageGb: 150,
    backups: 5,
    extraBackupSlots: 5,
    extraBackupPrice: "2.00",
    ports: 10,
    databases: 15,
    dedicatedIpPrice: "3.00",
    locations: ["Miami, Florida"],
    isPopular: false,
    sortOrder: 11,
  },
];

async function main() {
  const product = await prisma.product.upsert({
    where: { slug: "minecraft-hosting" },
    update: {
      name: "Minecraft Hosting",
      description: "Planes Minecraft de Gideon Hosting",
      status: "ACTIVE",
    },
    create: {
      name: "Minecraft Hosting",
      slug: "minecraft-hosting",
      description: "Planes Minecraft de Gideon Hosting",
      status: "ACTIVE",
    },
  });

  for (const [index, plan] of [...budgetPlans, ...performancePlans].entries()) {
    await prisma.plan.upsert({
      where: { slug: plan.slug },
      update: {
        ...plan,
        tier: index < budgetPlans.length ? "BUDGET" : "PERFORMANCE",
        productId: product.id,
        antiDdosIncluded: true,
      },
      create: {
        ...plan,
        tier: index < budgetPlans.length ? "BUDGET" : "PERFORMANCE",
        productId: product.id,
        antiDdosIncluded: true,
      },
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
